import type { CatalogMod } from "../types";

/**
 * Curated links only. STRYKER does not mirror third-party files and does not
 * invent download counts or ratings. Each entry sends the user to its author.
 */
export const VERIFIED_CATALOG_MODS: CatalogMod[] = [
  {
    id: "smokepatch-fl26",
    title: "SmokePatch Football Life 2026",
    author: "SmokePatch",
    version: "2.2",
    shortDesc: "Page officielle du jeu autonome Football Life 2026 et de ses mises à jour.",
    fullDesc: "Source officielle de Football Life 2026. L'installation et les mises à jour du jeu restent manuelles afin de respecter les instructions et les fichiers distribués par SmokePatch.",
    category: "other",
    compatibility: ["Football Life 2026"],
    size: "Voir la source",
    thumbnail: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2025/10/spfl26.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "jeu", "mise à jour"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-real-faces-2627",
    title: "Real Faces 2026/2027",
    author: "SmokePatch",
    version: "Update 4",
    shortDesc: "Pack officiel de visages destiné à Football Life 2026/2027.",
    fullDesc: "Pack de visages publié par SmokePatch. La page de l'auteur indique environ 37,4 Go installés. L'installation CPK reste manuelle et doit suivre les consignes officielles.",
    category: "face",
    compatibility: ["Football Life 2026", "Football Life 2027"],
    size: "37,4 Go installés",
    thumbnail: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2025/10/faces2627.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "visages", "CPK"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-sider-stadiums",
    title: "Football Life Sider Stadiums",
    author: "SmokePatch",
    version: "Source officielle",
    shortDesc: "Collection et instructions officielles pour les stades chargés par Sider.",
    fullDesc: "Ressources de stades Football Life avec contenu et fichiers de correspondance à installer selon les instructions de SmokePatch. STRYKER ouvre la source, puis permet d'importer un ZIP compatible séparément.",
    category: "turf",
    compatibility: ["Football Life", "Sider 7"],
    size: "Selon le stade",
    thumbnail: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2024/11/siderstadiums.html",
    screenshots: [],
    installationType: "mixed",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "stades", "Sider"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-commentaries",
    title: "Football Life Match Commentaries",
    author: "SmokePatch",
    version: "v9",
    shortDesc: "Packs officiels de commentaires audio pour Football Life.",
    fullDesc: "Page officielle des commentaires multilingues de Football Life. Les fichiers sont volumineux et leur procédure d'installation est spécifique : STRYKER renvoie donc vers les instructions originales.",
    category: "audio",
    compatibility: ["Football Life"],
    size: "Selon la langue",
    thumbnail: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2025/10/flcoms.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "commentaires", "audio"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-game-music",
    title: "Football Life Game Music",
    author: "SmokePatch",
    version: "Source officielle",
    shortDesc: "Pack musical alternatif publié pour Football Life.",
    fullDesc: "Ce pack utilise son propre programme d'installation. Par sécurité, STRYKER n'exécute jamais automatiquement les installateurs téléchargés et renvoie vers la procédure de l'auteur.",
    category: "audio",
    compatibility: ["Football Life"],
    size: "Voir la source",
    thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2024/06/BGM.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "musique", "manuel"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "holland-world-soccer",
    title: "World Soccer Gameplay Mod",
    author: "Holland",
    version: "Voir le sujet",
    shortDesc: "Mod de gameplay communautaire publié sur EvoWeb.",
    fullDesc: "Lien communautaire vers le sujet de l'auteur. La compatibilité exacte dépend de la version du jeu et des instructions du mod ; elle doit être vérifiée avant toute installation.",
    category: "gameplay",
    compatibility: ["PES 2021", "Football Life (à vérifier selon la version)"],
    size: "Voir la source",
    thumbnail: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://evoweb.uk/threads/new-gameplay-mod-world-soccer-world-soccer-2-new-update-available.84356/",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["communauté", "gameplay", "EvoWeb"],
    legalStatus: "community_external",
    verificationDate: "2026-08-30",
  },
];
