import type { CatalogMod } from "../types";

const STRYKER_RAW_REPOSITORY = "https://raw.githubusercontent.com/Itsadam99/stryker-football-life/main/public/repository/";

export const BUNDLED_CATALOG_MODS: CatalogMod[] = [
  {
    id: "eferq-graphic-menu-epl-2526",
    title: "Graphic Menu EPL 2025/26",
    author: "EFER.Q",
    version: "2025/26",
    shortDesc: "Menu graphique Premier League 2025/26 pour PES 2021 et Football Life 2026, préparé pour STRYKER.",
    fullDesc: "Pack complet avec Menu EPL, UIColors, module Lua et données content. Le paquet contrôlé est prêt, mais sa publication reste désactivée tant que l’autorisation de redistribution publique n’a pas été confirmée.",
    category: "menu",
    compatibility: ["PES 2021", "Football Life 2026", "Sider 7.3.4"],
    size: "127,1 Mo",
    thumbnail: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["menu", "Premier League", "EPL", "UIColors", "EFER.Q"],
    legalStatus: "unverified",
    verificationDate: "2026-08-31",
    archiveHash: "6b9ebfe5cdbbdcb8f10711feaaba17c8e839c57e6abe6b728c54196404771a8a",
    archiveSize: 133307293,
    fileCount: 87,
    status: "pending_review",
    sourceUrl: "https://pes-files.com/pes-2021-new-graphic-menu-epl-2025-26/",
    license: "Crédits : EFER.Q — autorisation de redistribution publique à confirmer avant hébergement.",
    repositoryUrl: STRYKER_RAW_REPOSITORY,
  },
  {
    id: "stryker-dlss5-controller",
    title: "STRYKER DLSS 5 Universal RTX Controller",
    author: "STRYKER",
    version: "1.2.0",
    shortDesc: "Contrôleur DLSS universel RTX 20 à 50 avec panneau F10 et installation vérifiée du patch legacy.",
    fullDesc: "Module Lua original et redistribuable. F10 ouvre directement le panneau Neural Rendering avec sept niveaux de qualité et exposition automatique. STRYKER détecte la génération du GPU : RTX 50 conserve la DLL NVIDIA native ; RTX 20/30/40 peut installer séparément la DLL épinglée après vérification exacte de son SHA-256 et sauvegarde de l’original. Aucun binaire NVIDIA n’est inclus dans ce ZIP.",
    category: "other",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "RenoDX DLSS SF 0.1", "GeForce RTX 20 / 30 / 40 / 50"],
    size: "5,0 Ko",
    thumbnail: "/mods/dlss5-cover.png",
    downloadUrl: "",
    screenshots: [],
    installationType: "automatic",
    rating: 0,
    downloadsCount: 0,
    tags: ["DLSS 5", "RenoDX", "Sider", "RTX 20/30/40/50", "contrôleur", "overlay"],
    legalStatus: "verified_package",
    verificationDate: "2026-09-01",
    archiveHash: "85f5ef90e0ed3862b6b22f7764b39c5c7db3971e0f5ebb69f5cab3a12dcb6cb8",
    archiveSize: 5071,
    fileCount: 4,
    status: "published",
    publishedAt: "2026-09-01T10:30:00.000Z",
    sourceUrl: "https://github.com/RankFTW/RHI",
    license: "MIT — code Lua STRYKER uniquement ; aucune DLL tierce incluse.",
  },
];

/**
 * Curated external links only. STRYKER does not mirror these third-party files
 * and does not invent download counts or ratings.
 */
export const VERIFIED_CATALOG_MODS: CatalogMod[] = [
  {
    id: "mega-facepack-v2-fl26-sider",
    title: "Mega Facepack V2 — FL26 Sider",
    author: "Communauté FaceMaker",
    version: "V2",
    shortDesc: "67 joueurs mis à jour avec des visages 3D pour Football Life 2026, dans un paquet Sider nettoyé et prêt pour STRYKER.",
    fullDesc: "L’archive fournie contient 67 joueurs crédités et 70 dossiers de visages exploitables. STRYKER a isolé les fichiers #Win réellement utilisés par le jeu, retiré un script de travail et écarté les sources inutiles. La fiche reste en prépublication tant que le droit de redistribuer publiquement le pack n’a pas été confirmé.",
    category: "face",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"],
    size: "30,3 Mo — paquet optimisé",
    thumbnail: "/mods/facepack-v2-cover.png",
    downloadUrl: "",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["67 joueurs", "visages 3D", "Sider", "LiveCPK"],
    legalStatus: "unverified",
    verificationDate: "2026-09-01",
    status: "pending_review",
    archiveHash: "cd0e3fe65273c7d9ea110b112472939161b8463c69a63199964de28c24144d90",
    archiveSize: 30300063,
    fileCount: 273,
    license: "Crédits conservés pour les FaceMakers listés dans l’archive d’origine. Autorisation de redistribution publique à confirmer avant hébergement.",
  },
  {
    id: "smokepatch-fl26",
    title: "SmokePatch Football Life 2026",
    author: "SmokePatch",
    version: "2.2",
    shortDesc: "Page officielle du jeu autonome Football Life 2026 et de ses mises à jour.",
    fullDesc: "Source officielle de Football Life 2026. L'installation et les mises à jour du jeu restent manuelles afin de respecter les instructions et les fichiers distribués par SmokePatch.",
    category: "other",
    compatibility: ["Football Life 2026"],
    size: "Voir la source",
    thumbnail: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2025/10/spfl26.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "jeu", "mise à jour"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-real-faces-2627",
    title: "Real Faces 2026/2027",
    author: "SmokePatch",
    version: "Update 4",
    shortDesc: "Pack officiel de visages destiné à Football Life 2026/2027.",
    fullDesc: "Pack de visages publié par SmokePatch. La page de l'auteur indique environ 37,4 Go installés. L'installation CPK reste manuelle et doit suivre les consignes officielles.",
    category: "face",
    compatibility: ["Football Life 2026", "Football Life 2027"],
    size: "37,4 Go installés",
    thumbnail: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2025/10/faces2627.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "visages", "CPK"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-sider-stadiums",
    title: "Football Life Sider Stadiums",
    author: "SmokePatch",
    version: "Source officielle",
    shortDesc: "Collection et instructions officielles pour les stades chargés par Sider.",
    fullDesc: "Ressources de stades Football Life avec contenu et fichiers de correspondance à installer selon les instructions de SmokePatch. STRYKER ouvre la source, puis permet d'importer un ZIP compatible séparément.",
    category: "turf",
    compatibility: ["Football Life", "Sider 7"],
    size: "Selon le stade",
    thumbnail: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2024/11/siderstadiums.html",
    screenshots: [],
    installationType: "mixed",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "stades", "Sider"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-commentaries",
    title: "Football Life Match Commentaries",
    author: "SmokePatch",
    version: "v9",
    shortDesc: "Packs officiels de commentaires audio pour Football Life.",
    fullDesc: "Page officielle des commentaires multilingues de Football Life. Les fichiers sont volumineux et leur procédure d'installation est spécifique : STRYKER renvoie donc vers les instructions originales.",
    category: "audio",
    compatibility: ["Football Life"],
    size: "Selon la langue",
    thumbnail: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2025/10/flcoms.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "commentaires", "audio"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "smokepatch-game-music",
    title: "Football Life Game Music",
    author: "SmokePatch",
    version: "Source officielle",
    shortDesc: "Pack musical alternatif publié pour Football Life.",
    fullDesc: "Ce pack utilise son propre programme d'installation. Par sécurité, STRYKER n'exécute jamais automatiquement les installateurs téléchargés et renvoie vers la procédure de l'auteur.",
    category: "audio",
    compatibility: ["Football Life"],
    size: "Voir la source",
    thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://www.pessmokepatch.com/2024/06/BGM.html",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["officiel", "musique", "manuel"],
    legalStatus: "verified_source",
    verificationDate: "2026-08-30",
  },
  {
    id: "renodx-dlss5-fl26-experimental",
    title: "DLSS 5 Neural Rendering — Football Life",
    author: "ShortFuse / communauté RenoDX",
    version: "SF 0.1 (expérimental)",
    shortDesc: "Guide expérimental DLSS Neural Rendering pour Football Life/PES 2021 sur GeForce RTX 50.",
    fullDesc: "Intégration communautaire non officielle et encore expérimentale. Testée localement sur Football Life 2026 en DirectX 11 avec une RTX 5060 : ReShade, RenoDX, NVIDIA NGX et le pont DX11 vers DX12 se chargent. STRYKER ouvre uniquement la publication amont et n'héberge aucune DLL ReShade, NVIDIA ou RenoDX ; l'installation reste manuelle et doit être réservée au jeu hors ligne.",
    category: "other",
    compatibility: ["Football Life 2026", "PES 2021", "DirectX 11", "GeForce RTX 50", "ReShade 6.8.0 Add-on"],
    size: "Téléchargements externes",
    thumbnail: "/mods/dlss5-cover.png",
    downloadUrl: "https://github.com/RankFTW/rhi-repo/releases/tag/renodx-dlss-SF-0.1",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["expérimental", "DLSS 5", "RenoDX", "ReShade", "RTX 50", "DX11"],
    legalStatus: "community_external",
    verificationDate: "2026-09-01",
    sourceUrl: "https://github.com/RankFTW/rhi-repo/releases/tag/renodx-dlss-SF-0.1",
    license: "Lien externe uniquement — aucun binaire ReShade, NVIDIA ou RenoDX n'est redistribué par STRYKER.",
  },
  {
    id: "holland-world-soccer",
    title: "World Soccer Gameplay Mod",
    author: "Holland",
    version: "Voir le sujet",
    shortDesc: "Mod de gameplay communautaire publié sur EvoWeb.",
    fullDesc: "Lien communautaire vers le sujet de l'auteur. La compatibilité exacte dépend de la version du jeu et des instructions du mod ; elle doit être vérifiée avant toute installation.",
    category: "gameplay",
    compatibility: ["PES 2021", "Football Life (à vérifier selon la version)"],
    size: "Voir la source",
    thumbnail: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1200&q=80",
    downloadUrl: "https://evoweb.uk/threads/new-gameplay-mod-world-soccer-world-soccer-2-new-update-available.84356/",
    screenshots: [],
    installationType: "manual",
    rating: 0,
    downloadsCount: 0,
    tags: ["communauté", "gameplay", "EvoWeb"],
    legalStatus: "community_external",
    verificationDate: "2026-08-30",
  },
];

type CatalogLanguage = "fr" | "en" | "pt" | "es";
type CatalogTranslation = Pick<CatalogMod, "shortDesc" | "fullDesc" | "version" | "compatibility" | "size" | "tags">;

const CATALOG_TRANSLATIONS: Record<Exclude<CatalogLanguage, "fr">, Record<string, CatalogTranslation>> = {
  en: {
    "mega-facepack-v2-fl26-sider": {
      shortDesc: "67 updated players with 3D faces for Football Life 2026, in a cleaned Sider package prepared for STRYKER.",
      fullDesc: "The supplied archive contains 67 credited players and 70 usable face folders. STRYKER isolated the #Win game files, removed one working script and discarded unused sources. This page remains a preview until public redistribution rights are confirmed.",
      version: "V2", compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"], size: "30.3 MB — optimized package", tags: ["67 players", "3D faces", "Sider", "LiveCPK"],
    },
    "smokepatch-fl26": {
      shortDesc: "Official page for the standalone Football Life 2026 game and its updates.",
      fullDesc: "Official Football Life 2026 source. Game installation and updates remain manual to respect the instructions and files distributed by SmokePatch.",
      version: "2.2", compatibility: ["Football Life 2026"], size: "View source", tags: ["official", "game", "update"],
    },
    "smokepatch-real-faces-2627": {
      shortDesc: "Official face pack for Football Life 2026/2027.",
      fullDesc: "Face pack published by SmokePatch. The author’s page indicates approximately 37.4 GB installed. CPK installation remains manual and must follow the official instructions.",
      version: "Update 4", compatibility: ["Football Life 2026", "Football Life 2027"], size: "37.4 GB installed", tags: ["official", "faces", "CPK"],
    },
    "smokepatch-sider-stadiums": {
      shortDesc: "Official collection and instructions for stadiums loaded through Sider.",
      fullDesc: "Football Life stadium resources with content and mapping files to install according to SmokePatch instructions. STRYKER opens the source and then lets you import a compatible ZIP separately.",
      version: "Official source", compatibility: ["Football Life", "Sider 7"], size: "Depends on the stadium", tags: ["official", "stadiums", "Sider"],
    },
    "smokepatch-commentaries": {
      shortDesc: "Official audio commentary packs for Football Life.",
      fullDesc: "Official page for Football Life’s multilingual commentary packs. The files are large and use a specific installation procedure, so STRYKER links to the original instructions.",
      version: "v9", compatibility: ["Football Life"], size: "Depends on the language", tags: ["official", "commentary", "audio"],
    },
    "smokepatch-game-music": {
      shortDesc: "Alternative music pack published for Football Life.",
      fullDesc: "This pack uses its own installer. For safety, STRYKER never runs downloaded installers automatically and links to the author’s procedure.",
      version: "Official source", compatibility: ["Football Life"], size: "View source", tags: ["official", "music", "manual"],
    },
    "holland-world-soccer": {
      shortDesc: "Community gameplay mod published on EvoWeb.",
      fullDesc: "Community link to the author’s thread. Exact compatibility depends on the game version and the mod instructions and must be checked before installation.",
      version: "View thread", compatibility: ["PES 2021", "Football Life (check for your version)"], size: "View source", tags: ["community", "gameplay", "EvoWeb"],
    },
    "renodx-dlss5-fl26-experimental": {
      shortDesc: "Experimental DLSS Neural Rendering guide for Football Life/PES 2021 on GeForce RTX 50.",
      fullDesc: "Unofficial community integration that is still experimental. Locally tested on Football Life 2026 in DirectX 11 with an RTX 5060: ReShade, RenoDX, NVIDIA NGX and the DX11-to-DX12 bridge load successfully. STRYKER only opens the upstream release and hosts no ReShade, NVIDIA or RenoDX DLL; installation remains manual and should be limited to offline play.",
      version: "SF 0.1 (experimental)", compatibility: ["Football Life 2026", "PES 2021", "DirectX 11", "GeForce RTX 50", "ReShade 6.8.0 Add-on"], size: "External downloads", tags: ["experimental", "DLSS 5", "RenoDX", "ReShade", "RTX 50", "DX11"],
    },
    "eferq-graphic-menu-epl-2526": {
      shortDesc: "Premier League 2025/26 graphic menu for PES 2021 and Football Life 2026, prepared for STRYKER.",
      fullDesc: "Complete package with Menu EPL, UIColors, a Lua module and content data. The verified package is ready, but publishing remains disabled until public redistribution permission is confirmed.",
      version: "2025/26", compatibility: ["PES 2021", "Football Life 2026", "Sider 7.3.4"], size: "127.1 MB", tags: ["menu", "Premier League", "EPL", "UIColors", "EFER.Q"],
    },
    "stryker-dlss5-controller": {
      shortDesc: "Universal RTX 20-to-50 DLSS controller with a dedicated F10 panel and verified legacy patch installation.",
      fullDesc: "Original redistributable Lua module. F10 opens the Neural Rendering panel. STRYKER detects the GPU generation: RTX 50 keeps the native NVIDIA DLL, while RTX 20/30/40 can install the separately downloaded pinned DLL after exact SHA-256 verification and backup. No NVIDIA binary is included in this ZIP.",
      version: "1.2.0", compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "RenoDX DLSS SF 0.1", "GeForce RTX 20 / 30 / 40 / 50"], size: "5 KB", tags: ["DLSS 5", "RenoDX", "Sider", "RTX 20/30/40/50", "controller", "overlay"],
    },
  },
  pt: {
    "mega-facepack-v2-fl26-sider": {
      shortDesc: "67 jogadores atualizados com rostos 3D para Football Life 2026, num pacote Sider limpo e preparado para o STRYKER.",
      fullDesc: "O arquivo fornecido contém 67 jogadores creditados e 70 pastas de rostos utilizáveis. O STRYKER isolou os ficheiros #Win, removeu um script de trabalho e descartou fontes desnecessárias. A página permanece em pré-publicação até os direitos de redistribuição pública serem confirmados.",
      version: "V2", compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"], size: "30,3 MB — pacote otimizado", tags: ["67 jogadores", "rostos 3D", "Sider", "LiveCPK"],
    },
    "smokepatch-fl26": {
      shortDesc: "Página oficial do jogo autónomo Football Life 2026 e das suas atualizações.",
      fullDesc: "Fonte oficial do Football Life 2026. A instalação e as atualizações do jogo continuam manuais para respeitar as instruções e os ficheiros distribuídos pela SmokePatch.",
      version: "2.2", compatibility: ["Football Life 2026"], size: "Ver fonte", tags: ["oficial", "jogo", "atualização"],
    },
    "smokepatch-real-faces-2627": {
      shortDesc: "Pack oficial de rostos para Football Life 2026/2027.",
      fullDesc: "Pack de rostos publicado pela SmokePatch. A página do autor indica cerca de 37,4 GB instalados. A instalação CPK continua manual e deve seguir as instruções oficiais.",
      version: "Atualização 4", compatibility: ["Football Life 2026", "Football Life 2027"], size: "37,4 GB instalados", tags: ["oficial", "rostos", "CPK"],
    },
    "smokepatch-sider-stadiums": {
      shortDesc: "Coleção e instruções oficiais para estádios carregados pelo Sider.",
      fullDesc: "Recursos de estádios do Football Life com conteúdo e ficheiros de correspondência para instalar segundo as instruções da SmokePatch. O STRYKER abre a fonte e permite importar separadamente um ZIP compatível.",
      version: "Fonte oficial", compatibility: ["Football Life", "Sider 7"], size: "Depende do estádio", tags: ["oficial", "estádios", "Sider"],
    },
    "smokepatch-commentaries": {
      shortDesc: "Packs oficiais de comentários áudio para Football Life.",
      fullDesc: "Página oficial dos comentários multilingues do Football Life. Os ficheiros são grandes e têm um procedimento de instalação específico, por isso o STRYKER encaminha para as instruções originais.",
      version: "v9", compatibility: ["Football Life"], size: "Depende do idioma", tags: ["oficial", "comentários", "áudio"],
    },
    "smokepatch-game-music": {
      shortDesc: "Pack de música alternativo publicado para Football Life.",
      fullDesc: "Este pack utiliza o seu próprio instalador. Por segurança, o STRYKER nunca executa automaticamente instaladores transferidos e encaminha para o procedimento do autor.",
      version: "Fonte oficial", compatibility: ["Football Life"], size: "Ver fonte", tags: ["oficial", "música", "manual"],
    },
    "holland-world-soccer": {
      shortDesc: "Mod de jogabilidade da comunidade publicado no EvoWeb.",
      fullDesc: "Ligação da comunidade para o tópico do autor. A compatibilidade exata depende da versão do jogo e das instruções do mod e deve ser verificada antes da instalação.",
      version: "Ver tópico", compatibility: ["PES 2021", "Football Life (verificar conforme a versão)"], size: "Ver fonte", tags: ["comunidade", "jogabilidade", "EvoWeb"],
    },
    "renodx-dlss5-fl26-experimental": {
      shortDesc: "Guia experimental de DLSS Neural Rendering para Football Life/PES 2021 em GeForce RTX 50.",
      fullDesc: "Integração comunitária não oficial e ainda experimental. Testada localmente no Football Life 2026 em DirectX 11 com uma RTX 5060: ReShade, RenoDX, NVIDIA NGX e a ponte DX11 para DX12 são carregados. O STRYKER apenas abre a publicação original e não aloja DLLs do ReShade, NVIDIA ou RenoDX; a instalação permanece manual e deve ser usada apenas no jogo offline.",
      version: "SF 0.1 (experimental)", compatibility: ["Football Life 2026", "PES 2021", "DirectX 11", "GeForce RTX 50", "ReShade 6.8.0 Add-on"], size: "Transferências externas", tags: ["experimental", "DLSS 5", "RenoDX", "ReShade", "RTX 50", "DX11"],
    },
    "eferq-graphic-menu-epl-2526": {
      shortDesc: "Menu gráfico da Premier League 2025/26 para PES 2021 e Football Life 2026, preparado para o STRYKER.",
      fullDesc: "Pack completo com Menu EPL, UIColors, módulo Lua e dados content. O pacote verificado está pronto, mas a publicação permanece desativada até ser confirmada a autorização de redistribuição pública.",
      version: "2025/26", compatibility: ["PES 2021", "Football Life 2026", "Sider 7.3.4"], size: "127,1 MB", tags: ["menu", "Premier League", "EPL", "UIColors", "EFER.Q"],
    },
    "stryker-dlss5-controller": {
      shortDesc: "Controlador DLSS universal RTX 20 a 50 com painel F10 e instalação verificada do patch legacy.",
      fullDesc: "Módulo Lua original e redistribuível. F10 abre o painel Neural Rendering. O STRYKER deteta a geração da GPU: RTX 50 conserva a DLL NVIDIA nativa; RTX 20/30/40 pode instalar separadamente a DLL afixada após verificação exata do SHA-256 e cópia de segurança. Nenhum binário NVIDIA está incluído neste ZIP.",
      version: "1.2.0", compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "RenoDX DLSS SF 0.1", "GeForce RTX 20 / 30 / 40 / 50"], size: "5 KB", tags: ["DLSS 5", "RenoDX", "Sider", "RTX 20/30/40/50", "controlador", "overlay"],
    },
  },
  es: {
    "mega-facepack-v2-fl26-sider": {
      shortDesc: "67 jugadores actualizados con caras 3D para Football Life 2026, en un paquete Sider limpio y preparado para STRYKER.",
      fullDesc: "El archivo suministrado contiene 67 jugadores acreditados y 70 carpetas de caras utilizables. STRYKER aisló los archivos #Win, eliminó un script de trabajo y descartó fuentes innecesarias. La ficha permanece en prepublicación hasta confirmar los derechos de redistribución pública.",
      version: "V2", compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"], size: "30,3 MB — paquete optimizado", tags: ["67 jugadores", "caras 3D", "Sider", "LiveCPK"],
    },
    "smokepatch-fl26": {
      shortDesc: "Página oficial del juego independiente Football Life 2026 y sus actualizaciones.",
      fullDesc: "Fuente oficial de Football Life 2026. La instalación y las actualizaciones del juego siguen siendo manuales para respetar las instrucciones y los archivos distribuidos por SmokePatch.",
      version: "2.2", compatibility: ["Football Life 2026"], size: "Ver fuente", tags: ["oficial", "juego", "actualización"],
    },
    "smokepatch-real-faces-2627": {
      shortDesc: "Pack oficial de caras para Football Life 2026/2027.",
      fullDesc: "Pack de caras publicado por SmokePatch. La página del autor indica unos 37,4 GB instalados. La instalación CPK sigue siendo manual y debe respetar las instrucciones oficiales.",
      version: "Actualización 4", compatibility: ["Football Life 2026", "Football Life 2027"], size: "37,4 GB instalados", tags: ["oficial", "caras", "CPK"],
    },
    "smokepatch-sider-stadiums": {
      shortDesc: "Colección e instrucciones oficiales para estadios cargados mediante Sider.",
      fullDesc: "Recursos de estadios de Football Life con contenido y archivos de correspondencia que deben instalarse según las instrucciones de SmokePatch. STRYKER abre la fuente y permite importar por separado un ZIP compatible.",
      version: "Fuente oficial", compatibility: ["Football Life", "Sider 7"], size: "Depende del estadio", tags: ["oficial", "estadios", "Sider"],
    },
    "smokepatch-commentaries": {
      shortDesc: "Packs oficiales de comentarios de audio para Football Life.",
      fullDesc: "Página oficial de los comentarios multilingües de Football Life. Los archivos son grandes y su instalación es específica, por lo que STRYKER enlaza las instrucciones originales.",
      version: "v9", compatibility: ["Football Life"], size: "Depende del idioma", tags: ["oficial", "comentarios", "audio"],
    },
    "smokepatch-game-music": {
      shortDesc: "Pack de música alternativo publicado para Football Life.",
      fullDesc: "Este pack utiliza su propio instalador. Por seguridad, STRYKER nunca ejecuta automáticamente los instaladores descargados y enlaza el procedimiento del autor.",
      version: "Fuente oficial", compatibility: ["Football Life"], size: "Ver fuente", tags: ["oficial", "música", "manual"],
    },
    "holland-world-soccer": {
      shortDesc: "Mod de jugabilidad comunitario publicado en EvoWeb.",
      fullDesc: "Enlace comunitario al tema del autor. La compatibilidad exacta depende de la versión del juego y de las instrucciones del mod y debe comprobarse antes de instalar.",
      version: "Ver tema", compatibility: ["PES 2021", "Football Life (comprobar según la versión)"], size: "Ver fuente", tags: ["comunidad", "jugabilidad", "EvoWeb"],
    },
    "renodx-dlss5-fl26-experimental": {
      shortDesc: "Guía experimental de DLSS Neural Rendering para Football Life/PES 2021 en GeForce RTX 50.",
      fullDesc: "Integración comunitaria no oficial y todavía experimental. Probada localmente en Football Life 2026 con DirectX 11 y una RTX 5060: ReShade, RenoDX, NVIDIA NGX y el puente de DX11 a DX12 se cargan correctamente. STRYKER solo abre la publicación original y no aloja ninguna DLL de ReShade, NVIDIA o RenoDX; la instalación sigue siendo manual y debe limitarse al juego sin conexión.",
      version: "SF 0.1 (experimental)", compatibility: ["Football Life 2026", "PES 2021", "DirectX 11", "GeForce RTX 50", "ReShade 6.8.0 Add-on"], size: "Descargas externas", tags: ["experimental", "DLSS 5", "RenoDX", "ReShade", "RTX 50", "DX11"],
    },
    "eferq-graphic-menu-epl-2526": {
      shortDesc: "Menú gráfico de la Premier League 2025/26 para PES 2021 y Football Life 2026, preparado para STRYKER.",
      fullDesc: "Pack completo con Menu EPL, UIColors, módulo Lua y datos content. El paquete verificado está listo, pero la publicación permanece desactivada hasta confirmar el permiso de redistribución pública.",
      version: "2025/26", compatibility: ["PES 2021", "Football Life 2026", "Sider 7.3.4"], size: "127,1 MB", tags: ["menú", "Premier League", "EPL", "UIColors", "EFER.Q"],
    },
    "stryker-dlss5-controller": {
      shortDesc: "Controlador DLSS universal RTX 20 a 50 con panel F10 e instalación verificada del parche legacy.",
      fullDesc: "Módulo Lua original y redistribuible. F10 abre el panel Neural Rendering. STRYKER detecta la generación de GPU: RTX 50 conserva la DLL NVIDIA nativa; RTX 20/30/40 puede instalar por separado la DLL fijada tras verificar exactamente su SHA-256 y guardar el original. Este ZIP no incluye ningún binario NVIDIA.",
      version: "1.2.0", compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "RenoDX DLSS SF 0.1", "GeForce RTX 20 / 30 / 40 / 50"], size: "5 KB", tags: ["DLSS 5", "RenoDX", "Sider", "RTX 20/30/40/50", "controlador", "overlay"],
    },
  },
};

export function localizeCatalogMod(mod: CatalogMod, language: CatalogLanguage): CatalogMod {
  if (language === "fr") return mod;
  const translation = CATALOG_TRANSLATIONS[language][mod.id];
  return translation ? { ...mod, ...translation } : mod;
}
