import type { CatalogMod } from "../types";

const STRYKER_MOD_REPOSITORY = "https://raw.githubusercontent.com/Itsadam99/stryker-football-life/main/public/repository/";
const STRYKER_MOD_RELEASE = "https://github.com/Itsadam99/stryker-football-life/releases/download/mods-2026.09/";

const preview = (mod: Omit<CatalogMod, "thumbnail" | "downloadUrl" | "screenshots" | "rating" | "downloadsCount" | "installationType" | "legalStatus" | "verificationDate" | "status">): CatalogMod => ({
  ...mod,
  thumbnail: "/stryker-logo.png",
  downloadUrl: "",
  screenshots: [],
  rating: 0,
  downloadsCount: 0,
  installationType: "automatic",
  legalStatus: "unverified",
  verificationDate: "2026-09-02",
  status: "pending_review",
});

const hosted = (mod: Parameters<typeof preview>[0], archiveFile: string): CatalogMod => ({
  ...preview(mod),
  downloadUrl: `${STRYKER_MOD_RELEASE}${archiveFile}`,
  repositoryUrl: STRYKER_MOD_REPOSITORY,
  legalStatus: "verified_package",
  status: "published",
  publishedAt: "2026-09-02T09:00:00.000Z",
});

export const DESKTOP_COMMUNITY_MODS: CatalogMod[] = [
  preview({
    id: "ficabre-goalnets-module-v1",
    title: "Ficabre Goalnets Module",
    author: "Ficabre",
    version: "1.0.0",
    shortDesc: "Filets 2025/26 complets avec physiques, formes, sons et préréglages par club, compétition et stade.",
    fullDesc: "Le module Sider comprend ses cartes, préréglages et ressources LiveCPK. STRYKER a retiré le script batch livré dans les sources et converti les 41 000 fichiers dans son format solide vérifié.",
    category: "turf",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7"],
    size: "745,6 Mo",
    tags: ["filets", "physique", "Sider", "LiveCPK", "2025/26"],
    archiveHash: "b438c46d4872237d1cc1369bf5b2adfe61c0f73162bce396030a0ff668ac7680",
    archiveSize: 781834716,
    fileCount: 41200,
    license: "Crédits : Ficabre — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
  preview({
    id: "shirtless-celebration-v4-1",
    title: "Shirtless Celebration",
    author: "alston2016",
    version: "4.1.0",
    shortDesc: "Célébration torse nu déclenchée avec R3, quatre modes de tenue et gestion automatique des carnations.",
    fullDesc: "Module Sider avec ressources LiveCPK, profils de joueurs et garde-fous de compatibilité. Il valide l’exécutable Football Life avant d’appliquer ses changements en mémoire et ne remplace jamais le fichier du jeu.",
    category: "other",
    compatibility: ["Football Life 2026", "Sider 7", "Build FL_2026 vérifié par le module"],
    size: "27,7 Mo",
    tags: ["célébration", "R3", "Sider", "overlay"],
    archiveHash: "b050eecc8c7559f3c1257ad4d312d2d0ba639da139e960c0d419af57bb4c3f2a",
    archiveSize: 29040982,
    fileCount: 67,
    license: "Crédits : alston2016 — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
  preview({
    id: "facepack-update-vol-204",
    title: "Facepack Update Vol. 204",
    author: "Communauté FaceMaker",
    version: "204",
    shortDesc: "Cinq visages : Rashford, Olise, Schmidt, Bouaddi et Querfeld.",
    fullDesc: "Pack LiveCPK optimisé par STRYKER : seuls les fichiers #Win réellement utilisés par Football Life/PES 2021 ont été conservés.",
    category: "face",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"],
    size: "2,2 Mo",
    tags: ["5 joueurs", "visages", "LiveCPK"],
    archiveHash: "ea9968b7c31ccefa632793cd5b203f37cc29872ef3cc167f55174b7b1c6548de",
    archiveSize: 2303453,
    fileCount: 12,
    license: "Crédits conservés — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
  preview({
    id: "facepack-update-vol-222",
    title: "Facepack Update Vol. 222",
    author: "Communauté FaceMaker",
    version: "222",
    shortDesc: "Cinq visages : N. Mendy, L. Dunk, C. Kouamé, Vinícius Jr et B. Mbeumo.",
    fullDesc: "Pack LiveCPK optimisé par STRYKER : seuls les fichiers #Win réellement utilisés par Football Life/PES 2021 ont été conservés.",
    category: "face",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"],
    size: "1,1 Mo",
    tags: ["5 joueurs", "visages", "LiveCPK"],
    archiveHash: "72f677b8cc61dcc0f1628041c0bda5a19b31ad39e49a374ec4bf24672fbb5916",
    archiveSize: 1164226,
    fileCount: 12,
    license: "Crédits conservés — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
  preview({
    id: "facepack-update-vol-223",
    title: "Facepack Update Vol. 223",
    author: "Communauté FaceMaker",
    version: "223",
    shortDesc: "Cinq visages : Klimowicz, Pedrosa, Sava, Sangaré et Espart.",
    fullDesc: "Pack LiveCPK optimisé par STRYKER : seuls les fichiers #Win réellement utilisés par Football Life/PES 2021 ont été conservés.",
    category: "face",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"],
    size: "1,4 Mo",
    tags: ["5 joueurs", "visages", "LiveCPK"],
    archiveHash: "c3008adbe2ccb05289a95dbc25ef9ac39e3f4ea652ca10d0bb5f69aa9446f2a7",
    archiveSize: 1497908,
    fileCount: 12,
    license: "Crédits conservés — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
  hosted({
    id: "premier-league-facepack-vol-1",
    title: "Premier League Facepack Vol. 1",
    author: "Nabilemu / Pudd Faceporting Workshop",
    version: "1.0.0",
    shortDesc: "Six visages Premier League : Tzolis, Mingueza, Röhl, George, Stach et Livramento.",
    fullDesc: "Conversions eFootball 2026 préparées pour PES 2021 et Football Life. Le pack a été optimisé pour LiveCPK et conserve le fichier de crédits et les liens de l’auteur.",
    category: "face",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"],
    size: "1,5 Mo",
    tags: ["Premier League", "6 joueurs", "visages", "LiveCPK"],
    archiveHash: "d4ab95cee4ec6c40792519bf689f177cd547748a8e253219782800dbf3726850",
    archiveSize: 1588677,
    fileCount: 14,
    sourceUrl: "https://evoweb.uk/threads/pudds-face-porting-workshop-2025-efootball-26-v5-4-0-and-fc26-face-conversion-here.95151/",
    license: "L’auteur autorise explicitement l’inclusion dans les patches/modpacks avec crédit.",
  }, "premier-league-facepack-vol-1.zip"),
  preview({
    id: "realism-menu-light-v2",
    title: "Realism Menu Light Mod",
    author: "Communauté Football Life",
    version: "2.0.0",
    shortDesc: "Éclairage de menu plus sobre pour l’accueil, l’édition et les écrans de match.",
    fullDesc: "Petit paquet LiveCPK nettoyé et normalisé pour une installation, une désactivation et une restauration gérées par STRYKER.",
    category: "menu",
    compatibility: ["Football Life 2026", "PES 2021", "Sider 7", "LiveCPK"],
    size: "199 Ko",
    tags: ["menu", "lumière", "LiveCPK"],
    archiveHash: "daaa15a040cca47b56520f8d050efb4de8493d48bf54083a912ae31bfb1b1d82",
    archiveSize: 203547,
    fileCount: 6,
    license: "Auteur non renseigné dans l’archive — autorisation de redistribution publique à confirmer.",
  }),
  preview({
    id: "fl26-pyro-supporters-v0-9a",
    title: "FL26 Pyro Supporters",
    author: "heazebell666",
    version: "0.9a",
    shortDesc: "Fumigènes et effets de tribunes avec couleurs par équipe et filtres de compétitions.",
    fullDesc: "Module Lua avec moteur de configuration, profils de couleurs et ressources Sider. STRYKER installe ensemble le module et son dossier content, puis peut les désactiver sans supprimer le paquet.",
    category: "other",
    compatibility: ["Football Life 2026", "Sider 7"],
    size: "6,4 Mo",
    tags: ["supporters", "fumigènes", "tribunes", "Sider"],
    archiveHash: "9c4be3f73863d51ee7c911c7296f0d39eb0cbd1fe219f41ca3ded6e918c43639",
    archiveSize: 6674941,
    fileCount: 59,
    license: "Crédits : heazebell666 — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
  preview({
    id: "fl26-pyro-no-spectator-patch",
    title: "FL26 Pyro — No Spectator Patch",
    author: "heazebell666",
    version: "1.0.0",
    shortDesc: "Patch optionnel qui retire les torches physiques des spectateurs sans supprimer fumée, feu ni lumière.",
    fullDesc: "Correctif complémentaire au pack FL26 Pyro Supporters. Son manifeste déclare la dépendance afin que STRYKER bloque l’activation si le module principal est absent ou désactivé.",
    category: "other",
    compatibility: ["Football Life 2026", "Sider 7", "FL26 Pyro Supporters 0.9a"],
    size: "1,4 Mo",
    tags: ["supporters", "patch", "torches", "dépendance"],
    archiveHash: "2989ce4c98b9a4fcd8d327108832801ca4b4e7ed2b7899918aad7637b06a7cfd",
    archiveSize: 1426945,
    fileCount: 12,
    license: "Crédits : heazebell666 — autorisation de redistribution publique à confirmer avant hébergement.",
  }),
];

type CommunityLanguage = "en" | "pt" | "es";
type CommunityTranslation = Pick<CatalogMod, "shortDesc" | "fullDesc" | "size" | "tags">;

export const DESKTOP_COMMUNITY_TRANSLATIONS: Record<CommunityLanguage, Record<string, CommunityTranslation>> = {
  en: {
    "ficabre-goalnets-module-v1": { shortDesc: "Complete 2025/26 nets with physics, shapes, sounds and presets by club, competition and stadium.", fullDesc: "The Sider module includes its maps, presets and LiveCPK resources. STRYKER removed the batch script found in the source and converted the 41,000-file pack to its verified solid format.", size: "745.6 MB", tags: ["nets", "physics", "Sider", "LiveCPK", "2025/26"] },
    "shirtless-celebration-v4-1": { shortDesc: "R3-triggered shirtless celebration with four outfit modes and automatic skin-tone handling.", fullDesc: "Sider module with LiveCPK resources, player profiles and compatibility safeguards. It validates the Football Life executable before applying in-memory changes and never replaces the game file.", size: "27.7 MB", tags: ["celebration", "R3", "Sider", "overlay"] },
    "facepack-update-vol-204": { shortDesc: "Five faces: Rashford, Olise, Schmidt, Bouaddi and Querfeld.", fullDesc: "LiveCPK pack optimized by STRYKER: only the #Win files used by Football Life/PES 2021 were kept.", size: "2.2 MB", tags: ["5 players", "faces", "LiveCPK"] },
    "facepack-update-vol-222": { shortDesc: "Five faces: N. Mendy, L. Dunk, C. Kouamé, Vinícius Jr and B. Mbeumo.", fullDesc: "LiveCPK pack optimized by STRYKER: only the #Win files used by Football Life/PES 2021 were kept.", size: "1.1 MB", tags: ["5 players", "faces", "LiveCPK"] },
    "facepack-update-vol-223": { shortDesc: "Five faces: Klimowicz, Pedrosa, Sava, Sangaré and Espart.", fullDesc: "LiveCPK pack optimized by STRYKER: only the #Win files used by Football Life/PES 2021 were kept.", size: "1.4 MB", tags: ["5 players", "faces", "LiveCPK"] },
    "premier-league-facepack-vol-1": { shortDesc: "Six Premier League faces: Tzolis, Mingueza, Röhl, George, Stach and Livramento.", fullDesc: "eFootball 2026 conversions prepared for PES 2021 and Football Life. The pack was optimized for LiveCPK and retains the author's credits and links.", size: "1.5 MB", tags: ["Premier League", "6 players", "faces", "LiveCPK"] },
    "realism-menu-light-v2": { shortDesc: "More restrained menu lighting for home, editing and match screens.", fullDesc: "Small LiveCPK package cleaned and normalized so STRYKER can install, disable and restore it.", size: "199 KB", tags: ["menu", "lighting", "LiveCPK"] },
    "fl26-pyro-supporters-v0-9a": { shortDesc: "Terrace smoke effects with team colors and competition filters.", fullDesc: "Lua module with configuration engine, color profiles and Sider resources. STRYKER installs the module and content folder together and can disable them without deleting the package.", size: "6.4 MB", tags: ["supporters", "smoke", "terraces", "Sider"] },
    "fl26-pyro-no-spectator-patch": { shortDesc: "Optional patch that removes physical spectator torches without removing smoke, fire or light.", fullDesc: "Companion fix for FL26 Pyro Supporters. Its manifest declares the dependency so STRYKER blocks activation when the main module is missing or disabled.", size: "1.4 MB", tags: ["supporters", "patch", "torches", "dependency"] },
  },
  pt: {
    "ficabre-goalnets-module-v1": { shortDesc: "Redes 2025/26 completas com física, formas, sons e predefinições por clube, competição e estádio.", fullDesc: "O módulo Sider inclui mapas, predefinições e recursos LiveCPK. O STRYKER removeu o script batch das fontes e converteu os 41 000 ficheiros para o seu formato sólido verificado.", size: "745,6 MB", tags: ["redes", "física", "Sider", "LiveCPK", "2025/26"] },
    "shirtless-celebration-v4-1": { shortDesc: "Celebração sem camisola acionada com R3, quatro modos e gestão automática de tons de pele.", fullDesc: "Módulo Sider com recursos LiveCPK, perfis de jogadores e proteções de compatibilidade. Valida o executável antes de alterar a memória e nunca substitui o ficheiro do jogo.", size: "27,7 MB", tags: ["celebração", "R3", "Sider", "overlay"] },
    "facepack-update-vol-204": { shortDesc: "Cinco rostos: Rashford, Olise, Schmidt, Bouaddi e Querfeld.", fullDesc: "Pack LiveCPK otimizado pelo STRYKER: apenas os ficheiros #Win usados pelo jogo foram mantidos.", size: "2,2 MB", tags: ["5 jogadores", "rostos", "LiveCPK"] },
    "facepack-update-vol-222": { shortDesc: "Cinco rostos: N. Mendy, L. Dunk, C. Kouamé, Vinícius Jr e B. Mbeumo.", fullDesc: "Pack LiveCPK otimizado pelo STRYKER: apenas os ficheiros #Win usados pelo jogo foram mantidos.", size: "1,1 MB", tags: ["5 jogadores", "rostos", "LiveCPK"] },
    "facepack-update-vol-223": { shortDesc: "Cinco rostos: Klimowicz, Pedrosa, Sava, Sangaré e Espart.", fullDesc: "Pack LiveCPK otimizado pelo STRYKER: apenas os ficheiros #Win usados pelo jogo foram mantidos.", size: "1,4 MB", tags: ["5 jogadores", "rostos", "LiveCPK"] },
    "premier-league-facepack-vol-1": { shortDesc: "Seis rostos da Premier League: Tzolis, Mingueza, Röhl, George, Stach e Livramento.", fullDesc: "Conversões do eFootball 2026 preparadas para PES 2021 e Football Life. O pack foi otimizado para LiveCPK e mantém os créditos e links do autor.", size: "1,5 MB", tags: ["Premier League", "6 jogadores", "rostos", "LiveCPK"] },
    "realism-menu-light-v2": { shortDesc: "Iluminação de menu mais discreta para ecrãs iniciais, de edição e de jogo.", fullDesc: "Pequeno pacote LiveCPK limpo e normalizado para instalação, desativação e restauro pelo STRYKER.", size: "199 KB", tags: ["menu", "iluminação", "LiveCPK"] },
    "fl26-pyro-supporters-v0-9a": { shortDesc: "Fumígenos nas bancadas com cores por equipa e filtros de competições.", fullDesc: "Módulo Lua com motor de configuração, perfis de cores e recursos Sider. O STRYKER instala módulo e conteúdo em conjunto e pode desativá-los sem apagar o pacote.", size: "6,4 MB", tags: ["adeptos", "fumígenos", "bancadas", "Sider"] },
    "fl26-pyro-no-spectator-patch": { shortDesc: "Patch opcional que remove tochas físicas dos espectadores sem retirar fumo, fogo ou luz.", fullDesc: "Correção complementar do FL26 Pyro Supporters. O manifesto declara a dependência para o STRYKER bloquear a ativação se o módulo principal faltar ou estiver desativado.", size: "1,4 MB", tags: ["adeptos", "patch", "tochas", "dependência"] },
  },
  es: {
    "ficabre-goalnets-module-v1": { shortDesc: "Redes 2025/26 completas con físicas, formas, sonidos y ajustes por club, competición y estadio.", fullDesc: "El módulo Sider incluye mapas, ajustes y recursos LiveCPK. STRYKER eliminó el script batch de las fuentes y convirtió los 41 000 archivos a su formato sólido verificado.", size: "745,6 MB", tags: ["redes", "física", "Sider", "LiveCPK", "2025/26"] },
    "shirtless-celebration-v4-1": { shortDesc: "Celebración sin camiseta con R3, cuatro modos y gestión automática de tonos de piel.", fullDesc: "Módulo Sider con recursos LiveCPK, perfiles de jugadores y protecciones de compatibilidad. Valida el ejecutable antes de cambiar la memoria y nunca reemplaza el archivo del juego.", size: "27,7 MB", tags: ["celebración", "R3", "Sider", "overlay"] },
    "facepack-update-vol-204": { shortDesc: "Cinco caras: Rashford, Olise, Schmidt, Bouaddi y Querfeld.", fullDesc: "Pack LiveCPK optimizado por STRYKER: solo se conservaron los archivos #Win utilizados por el juego.", size: "2,2 MB", tags: ["5 jugadores", "caras", "LiveCPK"] },
    "facepack-update-vol-222": { shortDesc: "Cinco caras: N. Mendy, L. Dunk, C. Kouamé, Vinícius Jr y B. Mbeumo.", fullDesc: "Pack LiveCPK optimizado por STRYKER: solo se conservaron los archivos #Win utilizados por el juego.", size: "1,1 MB", tags: ["5 jugadores", "caras", "LiveCPK"] },
    "facepack-update-vol-223": { shortDesc: "Cinco caras: Klimowicz, Pedrosa, Sava, Sangaré y Espart.", fullDesc: "Pack LiveCPK optimizado por STRYKER: solo se conservaron los archivos #Win utilizados por el juego.", size: "1,4 MB", tags: ["5 jugadores", "caras", "LiveCPK"] },
    "premier-league-facepack-vol-1": { shortDesc: "Seis caras de Premier League: Tzolis, Mingueza, Röhl, George, Stach y Livramento.", fullDesc: "Conversiones de eFootball 2026 preparadas para PES 2021 y Football Life. El pack está optimizado para LiveCPK y conserva los créditos y enlaces del autor.", size: "1,5 MB", tags: ["Premier League", "6 jugadores", "caras", "LiveCPK"] },
    "realism-menu-light-v2": { shortDesc: "Iluminación de menú más sobria para inicio, edición y pantallas de partido.", fullDesc: "Pequeño paquete LiveCPK limpiado y normalizado para que STRYKER pueda instalarlo, desactivarlo y restaurarlo.", size: "199 KB", tags: ["menú", "iluminación", "LiveCPK"] },
    "fl26-pyro-supporters-v0-9a": { shortDesc: "Bengalas de humo en las gradas con colores por equipo y filtros de competición.", fullDesc: "Módulo Lua con motor de configuración, perfiles de color y recursos Sider. STRYKER instala juntos el módulo y el contenido y puede desactivarlos sin borrar el paquete.", size: "6,4 MB", tags: ["afición", "humo", "gradas", "Sider"] },
    "fl26-pyro-no-spectator-patch": { shortDesc: "Parche opcional que elimina las antorchas físicas de espectadores sin quitar humo, fuego ni luz.", fullDesc: "Corrección complementaria para FL26 Pyro Supporters. Su manifiesto declara la dependencia para que STRYKER bloquee la activación si falta el módulo principal o está desactivado.", size: "1,4 MB", tags: ["afición", "parche", "antorchas", "dependencia"] },
  },
};
